name: Format
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'Widen/axe-reporter-html' }}
    steps:
      - uses: mskelton/setup-yarn@v1
      - run: yarn prettier --write .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
